# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Still Kicking ~ Still Tinkering
email: 
description: > # this means to ignore newlines until "baseurl:"
  A site describing the life of an idiot commited to karate and engineering.
  My name is Alex and am an studying Intergrated Mechanical and Electrical Engineering (IMEE)
  at the University of Bath. As could be guessed, my biggest passions in life are
  karate and engineering, followed closely by video/tabletop games.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neoxas.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  Neoxas

# Build settings
markdown: kramdown
